version: "3.9"

services:
  db:
    image: postgres:15
    container_name: petproject_db
    environment:
      POSTGRES_DB: pet_project
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser"]
      interval: 5s
      retries: 5
      timeout: 5s

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: petproject_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_NAME=pet_project
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
    volumes:
      - ./app:/app

volumes:
  postgres_data: